logging:
  level:
    dev:
      brice:
        nudleschoolmanagement: INFO
spring:
  application:
    name: nudleSchoolManagement
  jackson:
    default-property-inclusion: non_absent
server:
  port: 8080
